DROP SCHEMA PUBLIC CASCADE

CREATE TABLE Biologia(
id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
otazka varchar(1000),
odpoved_1 varchar(255),
odpoved_2 varchar(255),
odpoved_3 varchar(255),
odpoved_4 varchar(255),
odpoved_5 varchar(255),
odpoved_6 varchar(255),
odpoved_7 varchar(255),
odpoved_8 varchar(255),
jespravna_1 boolean,
jespravna_2 boolean,
jespravna_3 boolean,
jespravna_4 boolean,
jespravna_5 boolean,
jespravna_6 boolean,
jespravna_7 boolean,
jespravna_8 boolean,
);

CREATE TABLE Statistika_Biologia(
otazka_id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1)
);
CREATE TABLE users(
username varchar(1000)
);
insert into users (username) values ('default_user');
alter table Statistika_Biologia add default_user integer default '0'; 

alter table inzeraty alter column last_modified rename to time_inserted
alter table inzeraty add pocet_zobrazeni integer default '0' 

MYSQL:
CREATE TABLE statistika( 
id INT NOT NULL AUTO_INCREMENT, 
hostname varchar(20), 
appid varchar(10), 
stats varchar(6100), 
time_inserted timestamp,
PRIMARY KEY ( id ) );



alter table Inzeraty change last_modified time_inserted timestamp;
select * from Inzeraty where id=1;